theme: jekyll-theme-cayman
title: wujjjc's Blog
description: 推荐系统与深度学习的学习记录

# 导航
header_pages:
  - index.md
  - blog.md
  - tags.md

# 分类
collections:
  tech:
    output: true
  notes:
    output: true

# 标签
plugins:
  - jekyll-seo-tag

# 文章默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "wujjjc"
